# Generated by Django 3.0.3 on 2020-02-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
